src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $poster;

    /**
     * @ORM\Column(type="datetime")
     */
    private $releasedAt;

    /**
     * @ORM\Column(type="text")
     */
    private $synopsis;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="movies")
     */
    private $categories;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\People", mappedBy="actedIn")
     */
    private $actors;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\People", inversedBy="directed")
     */
    private $director;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Rating", mappedBy="movie", orphanRemoval=true)
     */
    private $ratings;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->actors = new ArrayCollection();
        $this->ratings = new ArrayCollection();
    }

    public function getAvgRatings(): float
    {
        return array_reduce(
            $this->ratings->toArray(),
            function ($total, Rating $rating) {
                return $total + $rating->getNotation();
            },
            0
        ) / count($this->ratings);
    }

    public function getSomeActors(?int $count = 3): array
    {
        return $this->actors->slice(0, $count);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getReleasedAt(): ?\DateTimeInterface
    {
        return $this->releasedAt;
    }

    public function setReleasedAt(\DateTimeInterface $releasedAt): self
    {
        $this->releasedAt = $releasedAt;

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }

    /**
     * @return Collection|People[]
     */
    public function getActors(): Collection
    {
        return $this->actors;
    }

    public function addActor(People $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors[] = $actor;
            $actor->addActedIn($this);
        }

        return $this;
    }

    public function removeActor(People $actor): self
    {
        if ($this->actors->contains($actor)) {
            $this->actors->removeElement($actor);
            $actor->removeActedIn($this);
        }

        return $this;
    }

    public function getDirector(): ?People
    {
        return $this->director;
    }

    public function setDirector(?People $director): self
    {
        $this->director = $director;

        return $this;
    }

    /**
     * @return Collection|Rating[]
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(Rating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setMovie($this);
        }

        return $this;
    }

    public function removeRating(Rating $rating): self
    {
        if ($this->ratings->contains($rating)) {
            $this->ratings->removeElement($rating);
            // set the owning side to null (unless already changed)
            if ($rating->getMovie() === $this) {
                $rating->setMovie(null);
            }
        }

        return $this;
    }
}

src/Entity/People.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PeopleRepository")
 */
class People
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"firstName","lastName"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $picture;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Movie", inversedBy="actors")
     */
    private $actedIn;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Movie", mappedBy="director")
     */
    private $directed;

    public function __construct()
    {
        $this->actedIn = new ArrayCollection();
        $this->directed = new ArrayCollection();
    }

    public function getFullName(): string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * @return Collection|Movie[]
     */
    public function getActedIn(): Collection
    {
        return $this->actedIn;
    }

    public function addActedIn(Movie $actedIn): self
    {
        if (!$this->actedIn->contains($actedIn)) {
            $this->actedIn[] = $actedIn;
        }

        return $this;
    }

    public function removeActedIn(Movie $actedIn): self
    {
        if ($this->actedIn->contains($actedIn)) {
            $this->actedIn->removeElement($actedIn);
        }

        return $this;
    }

    /**
     * @return Collection|Movie[]
     */
    public function getDirected(): Collection
    {
        return $this->directed;
    }

    public function addDirected(Movie $directed): self
    {
        if (!$this->directed->contains($directed)) {
            $this->directed[] = $directed;
            $directed->setDirector($this);
        }

        return $this;
    }

    public function removeDirected(Movie $directed): self
    {
        if ($this->directed->contains($directed)) {
            $this->directed->removeElement($directed);
            // set the owning side to null (unless already changed)
            if ($directed->getDirector() === $this) {
                $directed->setDirector(null);
            }
        }

        return $this;
    }
}

src/Entity/Rating.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RatingRepository")
 */
class Rating
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $comment;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Type(type="integer")
     */
    private $notation;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Movie", inversedBy="ratings")
     */
    private $movie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ratings")
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Like", mappedBy="rating")
     */
    private $likes;

    public function __construct()
    {
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getNotation(): ?int
    {
        return $this->notation;
    }

    public function setNotation(int $notation): self
    {
        $this->notation = $notation;

        return $this;
    }

    public function getMovie(): ?Movie
    {
        return $this->movie;
    }

    public function setMovie(?Movie $movie): self
    {
        $this->movie = $movie;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function hasLikeFromUser(User $user): bool
    {
        return $this->likes->filter(function (Like $like) use ($user) {
            return $like->getAuthor() === $user;
        })->count() > 0;
    }

    /**
     * @return Collection|Like[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function getPositiveLikes()
    {
        return $this->likes->filter(function (Like $like) {
            return $like->isPositive();
        });
    }

    public function getNegativeLikes()
    {
        return $this->likes->filter(function (Like $like) {
            return !$like->isPositive();
        });
    }

    public function addLike(Like $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setRating($this);
        }

        return $this;
    }

    public function removeLike(Like $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            // set the owning side to null (unless already changed)
            if ($like->getRating() === $this) {
                $like->setRating(null);
            }
        }

        return $this;
    }
}

src/Controller/MovieController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Category;
use App\Entity\Movie;
use App\Repository\CategoryRepository;
use App\Entity\Rating;
use App\Form\RatingType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use App\Repository\RatingRepository;
use App\Repository\MovieRepository;
use App\Entity\Like;

class MovieController extends AbstractController
{
    /**
     * @Route("/category/{slug}", name="movie_category")
     */
    public function showCategory(Category $category)
    {
        return $this->render('movie/category.html.twig', [
            'category' => $category
        ]);
    }

    /**
     * @Route("/movie/{slug}", name="movie_show")
     */
    public function showMovie(Movie $movie, Request $request, ObjectManager $manager, RatingRepository $ratingRepository)
    {

        $rating = new Rating();

        $form = $this->createForm(RatingType::class, $rating);

        $alreadyHasRating = (null != $ratingRepository->findOneBy(["movie" => $movie, "author" => $this->getUser()]));

        if (!$alreadyHasRating) {
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $rating->setAuthor($this->getUser())
                    ->setMovie($movie)
                    ->setCreatedAt(new \DateTime());

                $manager->persist($rating);
                $manager->flush();

                $this->redirectToRoute("movie_show", ["slug" => $movie->getSlug()]);
            }
        }

        return $this->render('movie/show.html.twig', [
            'movie' => $movie,
            'form' => $form->createView(),
            'alreadyHasRating' => $alreadyHasRating
        ]);
    }

    /**
     * @Route("/search", name="movie_search")
     */
    public function search(MovieRepository $movieRepository, Request $request)
    {
        $search = $request->query->get('q', '');

        $results = $movieRepository->findBySearch($search);

        return $this->render('movie/search.html.twig', [
            'results' => $results,
            'search' => $search
        ]);
    }

    /**
     * @Route("/rating/{id}/like", name="movie_rating_like")
     */
    public function ratingLike(Rating $rating, ObjectManager $manager)
    {
        $this->denyAccessUnlessGranted('ROLE_USER');

        $this->persistLike($rating, true);

        return $this->getJsonResponseForRatingLikes($rating);
    }

    /**
     * @Route("/rating/{id}/dislike", name="movie_rating_dislike")
     */
    public function ratingDislike(Rating $rating, ObjectManager $manager)
    {
        $this->denyAccessUnlessGranted('ROLE_USER');

        $this->persistLike($rating, false);

        return $this->getJsonResponseForRatingLikes($rating);
    }

    public function menuCategories(CategoryRepository $repo)
    {
        $categories = $repo->findAll();

        return $this->render('movie/_categories.html.twig', ['categories' => $categories]);
    }

    protected function getJsonResponseForRatingLikes(Rating $rating)
    {
        return $this->json(['positiveLikes' => $rating->getPositiveLikes()->count(), 'negativeLikes' => $rating->getNegativeLikes()->count()]);
    }

    protected function persistLike(Rating $rating, bool $isPositive = true)
    {
        if (!$rating->hasLikeFromUser($this->getUser())) {
            $like = new Like;
            $like->setRating($rating)
                ->setAuthor($this->getUser())
                ->setPositive($isPositive);

            $manager = $this->getDoctrine()->getManager();

            $manager->persist($like);
            $manager->flush();

            $manager->refresh($rating);
        }
    }
}

templates/movie/_categories.html.twig
{% for category in categories %}
    <li class="nav-item">
        <a class="nav-link" href="{{ path('movie_category', {'slug': category.slug}) }}">{{category.title}}</a>
    </li>
{% endfor %}

templates/movie/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les films de la catégorie `{{category.title}}` !
{% endblock %}

{% block body %}
    <h1>Les films de la catégorie
        <em>{{category.title}}</em>
    </h1>

    <hr>

    {% include "partials/_movies.html.twig" with {'movies': category.movies} %}
{% endblock %}

templates/movie/search.html.twig
{% extends "base.html.twig" %}

{% block title %}Recherche de `{{ search }}`
{% endblock %}

{% block body %}
    <h1>Résultats de la recherche
        <em>{{search}}</em>
        ({{results|length}}
        résultats)</h1>

    {% include "partials/_movies.html.twig" with {'movies': results} %}
{% endblock %}

templates/movie/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Fiche du film :
    {{movie.title}}
{% endblock %}

{% block body %}
    {% if movie.avgRatings > 2.5 %}
        {% set className = "badge-success" %}
    {% elseif movie.avgRatings > 1.5 %}
        {% set className = "badge-warning" %}
    {% else %}
        {% set className = "badge-danger" %}
    {% endif %}

    <h1 class="mb-5">{{movie.title}}
        ({{movie.director.fullName}},
        {{movie.releasedAt|date('Y')}})
        <span class="badge {{className}} float-right">
            Noté :
            {{ movie.avgRatings | number_format(2, ",", " ") }}
            / 5
        </span>
    </h1>

    <div class="row">
        <div class="col-4">
            <img src="{{movie.poster}}" alt="" class="img-fluid">
        </div>
        <div class="col">
            <h2>Synopsis du film :</h2>
            <p>{{ movie.synopsis}}</p>

            {% for category in movie.categories %}
                <a href="{{path('movie_category', {'slug': category.slug})}}" class="badge badge-dark">
                    {{ category.title }}
                </a>
            {% endfor %}


            <hr>
            <h2>Réalisé par
                {{movie.director.fullName}}</h2>

            <div class="row">
                <div class="col-3">
                    <img src="{{movie.director.picture}}" alt="">
                </div>
                <div class="col">
                    <strong>{{ movie.director.directed | length}}
                        films réalisé(s) :</strong>
                    <ul class="list-unstyled">
                        {% for movie in movie.director.directed %}
                            <li>
                                -
                                <a href="{{ path('movie_show', {'slug': movie.slug}) }}">
                                    {{ movie.title }}
                                    ({{movie.releasedAt | date('Y')}},
                                    {{movie.avgRatings | number_format(2, ","," ")}}
                                    / 5)
                                </a>

                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <hr>
            <h2>Casting :
            </h2>
            {% for actor in movie.actors %}
                <div class="mb-2">
                    <a href="{{ path('people_show', {'slug': actor.slug}) }}">
                        <img src="{{actor.picture}}" alt="" class="avatar avatar-mini mr-2">
                        {{actor.fullName}}
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <hr>

    {% if alreadyHasRating %}
        <h2>Vous avez déjà donné votre avis sur ce film</h2>
    {% else %}

        {% if is_granted('ROLE_USER') %}
            <h2>Donnez votre avis sur
                {{movie.title}}</h2>
            {{ form_start(form)}}

            {{ form_widget(form)}}

            <button class="btn btn-success" type="submit">
                <i class="fas fa-check"></i>
                Confirmer la notation
            </button>

            {{ form_end(form)}}

        {% else %}
            <h2>Connectez-vous si vous souhaitez donner votre avis sur le film</h2>
            <a href="{{ path('security_login') }}" class="btn btn-primary">
                <i class="fas fa-lock-open"></i>
                Connexion
            </a>
        {% endif %}
    {% endif %}

    <hr>
    <h2>{{movie.ratings | length}}
        critiques de la communauté
    </h2>

    {% for rating in movie.ratings %}
        <div>
            <strong>{{ rating.author.name }}</strong>
            <span class="badge badge-success">{{ rating.notation }}
                / 5</span>
            <blockquote>
                <em>{{ rating.comment }}</em>
            </blockquote>

            {% if is_granted('ROLE_USER') and not rating.hasLikeFromUser(app.user) %}
                <a class="badge badge-light text-dark" data-action="like" href="{{ path('movie_rating_like', {'id': rating.id}) }}">
                    <span>{{ rating.positiveLikes | length }}</span>&nbsp;
                    <i class="far fa-thumbs-up"></i>
                </a>

                <a class="badge badge-light text-dark" data-action="dislike" href="{{ path('movie_rating_dislike', {'id': rating.id}) }}">
                    <span>{{ rating.negativeLikes | length }}</span>&nbsp;
                    <i class="far fa-thumbs-down"></i>
                </a>
            {% else %}
                <span class="badge badge-dark">
                    {{ rating.positiveLikes | length }}&nbsp;
                    <i class="far fa-thumbs-up"></i>
                </span>

                <span class="badge badge-dark">
                    {{ rating.negativeLikes | length }}&nbsp;
                    <i class="far fa-thumbs-down"></i>
                </span>

            {% endif %}
            <hr>
        </div>

    {% endfor %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script type="text/javascript">
        // Je vais chercher tous les liens qui ont un attribut data-action qui contient le mot like
        document.querySelectorAll("a[data-action*='like']").forEach(link => { // Pour chaque lien, je créé un événement sur le click
            link.addEventListener('click', e => { // J'annule le comportement par défaut du click
                e.preventDefault();

                // Je récupère le href du lien
                const href = link.href;
                const action = link.dataset.action;

                // Si on a bien un href (les liens déjà cliqués n'ont plus de href)
                if (href) { // On appelle l'URL en AJAX et on récupère la réponse en JSON
                    fetch(href).then(response => response.json()).then(data => { // Regardez la console pour voir ce que le controller a renvoyé
                        console.log(data);
                        // On change le nombre de likes / dislikes
                        link.querySelector('span').textContent = (action === 'like' ? data.positiveLikes : data.negativeLikes);
                        // On change l'apparence du bouton
                        link.classList.remove('badge-light', 'text-dark');
                        link.classList.add('badge-dark', 'text-light');
                        // On supprime le href pour qu'on ne puisse pas recliquer sur le bouton
                        link.removeAttribute('href');
                    });
                }

            })
        })
    </script>
{% endblock %}